=== Qworel97/JavaCourse/Practice07/input.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://nure.ua/shevchenko/Practice7/entity" 
	xmlns:tns="http://nure.ua/shevchenko/Practice7/entity">

	<xsd:element name="ContributionsCollection">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Bank" 
					type="tns:Bank" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="Bank">
		<xsd:sequence>
			<xsd:element name="Name" type="xsd:string" />
			<xsd:element name="Country" type="xsd:string" />
			<xsd:element name="Type" type="tns:Types" />
			<xsd:element name="Depositor" type="xsd:string" />
			<xsd:element name="AccountId" type="xsd:int" />
			<xsd:element name="AmountOnDeposit" type="xsd:decimal" />
			<xsd:element name="Profitability" type="tns:Profit" />	
			<xsd:element name="TimeConstraints" type="xsd:dateTime" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="Profit">
		<xsd:restriction base="xsd:decimal">
      			<xsd:minInclusive value="0"/>
      			<xsd:maxInclusive value="1"/>
    		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="Types">
    		<xsd:restriction base="xsd:string">
        		<xsd:enumeration value="Poste restante" />
        		<xsd:enumeration value="Urgent" />
        		<xsd:enumeration value="Checking account" />
        		<xsd:enumeration value="Cumulative" />
       			<xsd:enumeration value="Savings" />
        		<xsd:enumeration value="Metal" />
    		</xsd:restriction>
	</xsd:simpleType>
	
</xsd:schema>

=== Qworel97/JavaCourse/Practice7/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<st3:ContributionsCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:st3="http://nure.ua/shevchenko/Practice7/entity"
		xsi:schemaLocation="http://nure.ua/shevchenko/Practice7/entity input.xsd">			
		
	<Bank>	
		<Name>Test1</Name>
		<Country>Test</Country>
		<Type>Poste restante</Type>
		<Depositor>Test</Depositor>
		<AccountId>2</AccountId>
		<AmountOnDeposit>31.0</AmountOnDeposit>
		<Profitability>0.05</Profitability>
		<TimeConstraints>2001-10-26T21:32:52</TimeConstraints>
	</Bank>		
	
		<Bank>	
		<Name>Test3</Name>
		<Country>Test</Country>
		<Type>Urgent</Type>
		<Depositor>Test</Depositor>
		<AccountId>2</AccountId>
		<AmountOnDeposit>3.0</AmountOnDeposit>
		<Profitability>0.2</Profitability>
		<TimeConstraints>2001-10-26T21:32:52</TimeConstraints>
	</Bank>		
	
	<Bank>	
		<Name>Test2</Name>
		<Country>Test</Country>
		<Type>Checking account</Type>
		<Depositor>Test</Depositor>
		<AccountId>2</AccountId>
		<AmountOnDeposit>333.0</AmountOnDeposit>
		<Profitability>0.1</Profitability>
		<TimeConstraints>2001-10-26T21:32:52</TimeConstraints>
	</Bank>	
	
	<Bank>	
		<Name>Test4</Name>
		<Country>Test</Country>
		<Type>Savings</Type>
		<Depositor>Test</Depositor>
		<AccountId>2</AccountId>
		<AmountOnDeposit>3421.0</AmountOnDeposit>
		<Profitability>0.25</Profitability>
		<TimeConstraints>2001-10-26T21:32:52</TimeConstraints>
	</Bank>	
	
</st3:ContributionsCollection>
